module.exports = {
  env: {
    DERIBIT_CLIENT_ID: process.env.DERIBIT_CLIENT_ID,
    DERIBIT_CLIENT_SECRET: process.env.DERIBIT_CLIENT_SECRET,
    DERIBIT_API_URL: process.env.DERIBIT_API_URL,
    GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY,
    GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
    GOOGLE_SPREADSHEET_ID: process.env.GOOGLE_SPREADSHEET_ID,
    GOOGLE_SHEET_ID: process.env.GOOGLE_SHEET_ID,
    DEVELOPMENT_DOMAIN: process.env.DEVELOPMENT_DOMAIN,
  },
};
