name: DEV CI

on:
  push:
    branches:
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Jest Test
        run: yarn jest-test

      - name: Cypress Test
        run: yarn cypress-test

      - name: send default failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: "@ShieldmasterBot"
          token: ${{ secrets.TELEGRAM_TOKEN }}
          
      - name: send success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: "@ShieldmasterBot"
          token: ${{ secrets.TELEGRAM_TOKEN }}

  deploy:
    if: ${{ github.ref == 'refs/heads/dev' }}
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        architecture: [x64]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Vercel Preview 
        if: github.ref == 'refs/heads/dev'
        uses: amondnet/vercel-action@v20
        id: vercel-deployment
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-project-name: "SF_APP"
